scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
