- name: Setup EC2 instance
  hosts: ec2_instances
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    git_repository: "https://github.com/SimonelDavid/HeatIslands.git"
    local_key_path: "../../git-crypt-key"
    remote_key_path: "/tmp/git-crypt-key"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install necessary packages (Debian)
      apt:
        name:
          - git
          - git-crypt
          - docker
          - docker-compose
        state: present
      become: true

    - name: Get list of all Docker containers
      command: docker ps -a -q
      register: docker_container_list
      changed_when: false

    - name: Get list of all Docker images
      command: docker images -q
      register: docker_image_list
      changed_when: false

    - name: Stop all Docker containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_container_list.stdout_lines }}"
      ignore_errors: yes

    - name: Remove all Docker containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_container_list.stdout_lines }}"
      ignore_errors: yes

    - name: Remove all Docker images
      command: sudo docker rmi "{{ item }}"
      loop: "{{ docker_image_list.stdout_lines }}"
      ignore_errors: yes

    - name: Ensure the private key is present
      copy:
        src: "{{ playbook_dir }}/../terraform/heat_island.pem"
        dest: "/tmp/heat_island.pem"
        mode: '0600'

    - name: Transfer the git-crypt key to the instance
      copy:
        src: "{{ local_key_path }}"
        dest: "{{ remote_key_path }}"
        mode: '0600'
      
    - name: Delete existing repository if it exists
      file:
        path: "/opt/HeatIslands"
        state: absent

    - name: Clone the repository at a specific commit
      git:
        repo: "{{ git_repository }}"
        dest: "/opt/HeatIslands"
        # version: "22e392fd45c888c97a183c18281187a087bd9271"
        clone: yes

    - name: Unlock the repository
      command: git-crypt unlock "{{ remote_key_path }}"
      args:
        chdir: "/opt/HeatIslands"

    - name: Run docker-compose up
      docker_compose:
        project_src: "/opt/HeatIslands"
        state: present
