---
- name: Setup EC2 instance
  hosts: ec2_instances
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    git_repository: "https://github.com/SimonelDavid/HeatIslands.git"
    local_key_path: "../../git-crypt-key"
    remote_key_path: "/tmp/git-crypt-key"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install necessary packages (Debian)
      apt:
        name:
          - git
          - git-crypt
          - docker
          - docker-compose
        state: present
      become: true

    - name: Ensure the private key is present
      copy:
        src: "{{ playbook_dir }}/../terraform/heat_island.pem"
        dest: "/tmp/heat_island.pem"
        mode: '0600'

    - name: Transfer the git-crypt key to the instance
      copy:
        src: "{{ local_key_path }}"
        dest: "{{ remote_key_path }}"
        mode: '0600'

    - name: Clone the repository
      git:
        repo: "{{ git_repository }}"
        dest: "/opt/HeatIslands"
        clone: yes

    - name: Unlock the repository
      command: git-crypt unlock "{{ remote_key_path }}"
      args:
        chdir: "/opt/HeatIslands"

    - name: Run docker-compose up
      docker_compose:
        project_src: "/opt/HeatIslands"
        state: present
